#!/usr/bin/python

import random

class EasyPassword(object):

    # let's use y as a phonetic vowel here...
    vowels_lefthand = "aey"
    vowels_righthand = "iou"
    consonants_lefthand = "qwrtsdfgxcvb"
    consonants_righthand = "zhnjmklp"
    numbers_lefthand = "123456"
    numbers_righthand = "7890"

    def __init__(self):
        self.result = ""
        self.buildpassword()
        print self.result

    def buildpassword(self):
        self.result += random.choice(self.consonants_righthand)
        self.result += random.choice(self.vowels_lefthand)
        self.result += random.choice(self.consonants_righthand)
        self.result += random.choice(self.consonants_lefthand)
        self.result += random.choice(self.vowels_righthand)
        self.result += random.choice(self.consonants_lefthand)
        self.result += random.choice(self.numbers_righthand)
        self.result += random.choice(self.numbers_lefthand)


a = EasyPassword()


